### ISSUE TITLE
Publish release?

### ISSUE THREAD

**Issue by fimbulvetr** [wdtamagi/svelte-avatar#7]
Hello, 

I noticed there has not been a new release that contains the latest features (random bg color). The latest on npm is 1.0.6, and there are recent prs and commits that haven't been published.

**Comment by wdtamagi** [comment]
Hello @fimbulvetr  thanks for your time to open a issue,

Sorry for that, I thought that I published a new version, i will publish a new one today ;)

**Comment by wdtamagi** [comment]
Released svelte-avatar@1.1.0 :1st_place_medal: 
Thanks for report @fimbulvetr 
Just let me know if it's with new features now.

**Comment by fimbulvetr** [comment]
> Released svelte-avatar@1.1.0 
> Thanks for report @fimbulvetr
> Just let me know if it's with new features now.

Thank you, but I'm sorry to say there is a pretty major bug now as util.js wasn't included in the package.

```
✗ client
Could not resolve './utils.js' from node_modules/svelte-avatar/src/Avatar.svelte
✗ server
Could not resolve './utils.js' from node_modules/svelte-avatar/src/Avatar.svelte
internal/modules/cjs/loader.js:883
  throw err;
```

```
$ ls -R node_modules/svelte-avatar/
node_modules/svelte-avatar/:
LICENSE  package.json  README.md  src

node_modules/svelte-avatar/src:
Avatar.svelte
```

Thank you!

**Comment by wdtamagi** [comment]
Sorry for the big delay to reply, I will fix it today.

**Comment by wdtamagi** [comment]
Generated version 1.1.1 can you take a look again @fimbulvetr ?

**Comment by wdtamagi** [comment]
Seems to be fixed with the new version (https://github.com/wdtamagi/svelte-avatar/issues/8).

If you have any issue please let me know, and sorry again for the delay... :(
