### ISSUE TITLE
Does not work for me with version 1.1.0

### ISSUE THREAD

**Issue by StefanBuerscher** [wdtamagi/svelte-avatar#8]
With Version 1.1.0 it shows "Module not found: Error: Can't resolve './utils.js' in" at build.
It works with 1.0.6

**Comment by wdtamagi** [comment]
Thanks for the report I will take a look soon.

**Comment by wdtamagi** [comment]
@StefanBuerscher, we released new 1.1.1 version, can you check if it works?

**Comment by StefanBuerscher** [comment]
It works with your new version. Thanks!

**Comment by wdtamagi** [comment]
Great to know that! thanks for your report ;)
